name: Comment on PR

env:
  GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

on:
  pull_request:
    branches:
    - master

jobs:
  pr_comment:
    runs-on: ubuntu-latest
    name: Add a comment to new PRs
    steps:
      - uses: hamstu/github-action-pr-comment@v1
