name: Cypress

on: [repository_dispatch]

jobs:
  cypress:
    name: Cypress
    runs-on: ubuntu-latest
    steps:             
    - name: Bail out if unexpected action
      if: github.event.action != 'bufferbotbrains'
      run: exit 1
    
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.event.client_payload.sha }}

    - name: Set status to pending
      uses: actions/github-script@0.8.0
      with:
        script: |
          console.log(context);
