name: Bufferbot Helper

on:
  pull_request:
    branches:
    - master

jobs:
  pr_comment:
    runs-on: ubuntu-latest
    name: Add helpful comment to new PRs
    steps:
      - uses: bufferapp/github-action-bufferbot-helper@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          staging-url-template: "https://{{placeholder}}-publish.dev.buffer.com"
          service-name: "buffer-publish"
