name: Dispatch Test

on: [repository_dispatch]

jobs:
  dispatch-test:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "${{ github.event.action }}"
          echo "${{ toJson(github.event.client_payload) }}"
