name: Cypress

on: [repository_dispatch]

jobs:
  cypress:
    name: "Cypress"
    runs-on: ubuntu-latest
    steps:             
    - name: Bail out if not correct action
      if: github.event.action != 'bufferbotbrains'
      run: exit 1

    - name: Log Payload
      run: echo "${{ toJson(github.event) }}"
